services:
  - type: web
    name: ghl-contact-service
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GHL_API_KEY
        sync: false
      - key: GHL_LOCATION_ID
        sync: false
      - key: GHL_BASE_URL
        value: https://rest.gohighlevel.com/v1
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true